name: CD pipeline for mpbot

env:
  APP_NAME: "mpbot"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to the server via ssh
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deploy
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/deploy
            if [ -d ${{ env.APP_NAME }}/.git ]; then
              echo "repository already exists, pulling changes..."
              cd ${{ env.APP_NAME }}
              git pull origin master
            else
              echo "cloning repository for the first time.."
              git clone https://github.com/ensomnatt/${{ env.APP_NAME }}
              cd ${{ env.APP_NAME }}
            fi

            if [ ! -f .env ]; then
              echo "creating .env file..."
              echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
              echo "CHANNEL_ID=-1002695794179" >> .env
              echo "SCHEDULE_START=20:00" >> .env
              echo "SCHEDULE_END=7:00" >> .env
              echo "INTERVAL=5" >> .env
              echo "TIME_ZONE="Europe/Moscow"" >> .env
              echo "START_MESSAGE="привет, я твой вп бот"" >> .env
            fi

            docker compose down
            docker compose up --build -d --remove-orphans
